name: Xbox Deals Price Checker

on:
  schedule:
    - cron: "0 */3 * * *"  # Ejecutar cada 3 horas (UTC)
  workflow_dispatch:       # Permite ejecución manual desde GitHub

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Xbox price checker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
